version: '3.7'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/vhost.d:/etc/nginx/vhost.d:ro
      - ./nginx/html:/usr/share/nginx/html:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - app

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/html:/var/www/html
    entrypoint: /bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait ${!}; done;'
    depends_on:
      - nginx

  app:
    build: .
    image: app
    volumes:
      - app-storage:/rails/storage
    environment:
      - RAILS_MASTER_KEY=76ffba0370aeea3b6a3971f1f6309674
    labels:
      - "traefik.enable=false" # if you still have traefik labels, disable them
    networks:
      - web

networks:
  web:
    external: true

volumes:
  app-storage:
